name: main
on: push
jobs:
  main:
    name: Bazel build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
  # - uses: actions/checkout@v3
  # - name: Mount bazel cache
  #   uses: actions/cache@v3
  #   with:
  #     path: "/home/runner/.cache/bazel"
  #     key: bazel
    - name: Build and Test
      run: 
        bazel build //...
        # bazel test //..
